name: Build Images

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - Dockerfile
      - init.sh
  pull_request:
    branches:
      - master
    paths:
      - Dockerfile
      - init.sh

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   - name: checkout repo
     uses: actions/checkout@main

   - name: build container
     run: make publish DOCKER_USER=${{ secrets.DOCKER_USER }} DOCKER_PASS=${{ secrets.DOCKER_TOKEN }}