name: build-images

on:
  push:
    paths:
      - Dockerfile
      - init.sh
  pull_request:
    paths:
      - Dockerfile
      - init.sh

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   - name: checkout repo
     uses: actions/checkout@main

   - name: Analyze with shellcheck
     run: docker run --rm -v $(pwd):/script koalaman/shellcheck:stable /script/init.sh

   - name: build container
     run: make publish DOCKER_USER=${{ secrets.DOCKER_USER }} DOCKER_PASS=${{ secrets.DOCKER_TOKEN }}