name: Issue Builder
on:
  workflow_dispatch:
  issues:
    types: [opened, labeled]

jobs:
  issue-handler:
    if: ${{ github.event.issues.labels.*.name }} == "trigger-build"
    runs-on: ubuntu-latest

    steps:
      - name: Trigger build workflow
        run: |
          echo "Triggering the build workflow..."
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https:// api.github.com/repos/${{ github.repository }}/actions/workflows/build.yaml/dispatches \
            -d '{"ref": "main"}'
    
      - name: Get workflow ID
        id: get_workflow_id
        run: |
          build_run_id=$(curl -s \
            -H "Authorization: Bearer: ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs \
            | jq '.workflow_runs[] | select(.name == "Build Images") | .id' | head -n 1)
          echo "Build run ID: $build_run_id"
          echo "::set-output name=build_run_id::$build_run_id"

  issue-resolver:
    needs: issue-handler
    runs-on: ubuntu-latest
    steps:
      - name: Check build status
        id: check_build_status
        run: |
          build_run_id=${{ needs.issue-handler.outputs.build_run_id }}

          while true; do
            status=$(curl -s \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/actions/runs/$build_run_id \
              | jq -r '.status')
            
            conclusion=$(curl -s \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/actions/runs/$build_run_id \
              | jq -r '.conclusion')

            echo "Build status: $status"
            echo "Build conclusion: $conclusion"

            if [[ "$status" == "completed" ]]; then
              if [[ "$conclusion" == "success" ]]; then
                echo "Build succeeded"
                build_result="success"
                break
              elif [[ "$conclusion" == "failure" ]]; then
                echo "Build failed"
                build_result="failure"
                break
              fi
            else
              echo "Build still in progress, waiting 30 seconds..."
              sleep 30
            fi
          done

      - name: Close issue on success
        if: ${{ steps.check_build_status.outputs.build_result }} == "success"
        uses: peter-evans/close-issue@main
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: "Build completed, this issue will now automatically resolve."
          close-issue: true
    
      - name: Add comment on failure
        if: ${{ steps.check_build_status.outputs.build_result }} == "failure"
        uses: peter-evans/create-or-update-comment@main
        with:
          issue-number: ${{ github.event.issue.number }}
          body: "Build failed. Please check the logs for details"